package org.grimmory.magic4j;

import static org.junit.jupiter.api.Assertions.*;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.zip.CRC32;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;
import javax.sound.sampled.AudioFileFormat;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class FormatDetectionTest {

  // PNG: \x89PNG\r\n\x1a\n + minimal IHDR marker
  private static final byte[] PNG = {
    (byte) 0x89,
    0x50,
    0x4E,
    0x47,
    0x0D,
    0x0A,
    0x1A,
    0x0A,
    0x00,
    0x00,
    0x00,
    0x0D,
    0x49,
    0x48,
    0x44,
    0x52
  };

  // JPEG: FF D8 FF E0 + JFIF marker
  private static final byte[] JPEG = {
    (byte) 0xFF,
    (byte) 0xD8,
    (byte) 0xFF,
    (byte) 0xE0,
    0x00,
    0x10,
    0x4A,
    0x46,
    0x49,
    0x46,
    0x00,
    0x01
  };

  // GIF89a
  private static final byte[] GIF = {
    0x47, 0x49, 0x46, 0x38, 0x39, 0x61, 0x01, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x3B
  };

  // TIFF little-endian ("II*\0")
  private static final byte[] TIFF_LE = {0x49, 0x49, 0x2A, 0x00, 0x08, 0x00, 0x00, 0x00};

  // TIFF big-endian ("MM\0*")
  private static final byte[] TIFF_BE = {0x4D, 0x4D, 0x00, 0x2A, 0x00, 0x00, 0x00, 0x08};

  // SVG (XML with SVG namespace enough for content-type detection)
  private static final byte[] SVG =
      ("<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
              + "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"10\" height=\"10\"></svg>")
          .getBytes(StandardCharsets.UTF_8);

  // FLAC: "fLaC" signature + STREAMINFO block header (42 bytes total)
  private static final byte[] FLAC = buildFlacBytes();

  private static byte[] buildFlacBytes() {
    byte[] b = new byte[42];
    b[0] = 0x66;
    b[1] = 0x4C;
    b[2] = 0x61;
    b[3] = 0x43; // "fLaC"
    b[4] = (byte) 0x80; // last=true, type=0 (STREAMINFO)
    b[5] = 0x00;
    b[6] = 0x00;
    b[7] = 0x22; // block length = 34
    return b;
  }

  // RAR v4 signature: "Rar!\x1a\x07\x00"
  private static final byte[] RAR_V4 = {0x52, 0x61, 0x72, 0x21, 0x1A, 0x07, 0x00};

  // RAR v5 signature: "Rar!\x1a\x07\x01\x00"
  private static final byte[] RAR_V5 = {0x52, 0x61, 0x72, 0x21, 0x1A, 0x07, 0x01, 0x00};

  // 7-Zip: "7z\xBC\xAF\x27\x1C"
  private static final byte[] SEVENZIP = {
    0x37, 0x7A, (byte) 0xBC, (byte) 0xAF, 0x27, 0x1C, 0x00, 0x03
  };

  // GZip: magic bytes + deflate method
  private static final byte[] GZIP = {
    0x1F, (byte) 0x8B, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, (byte) 0xFF
  };

  // MOBI/PalmDB: "BOOKMOBI" at offset 60 (type="BOOK" + creator="MOBI")
  private static final byte[] MOBI = buildMobiBytes();

  private static byte[] buildMobiBytes() {
    byte[] b = new byte[78]; // minimal PalmDB header
    b[60] = 'B';
    b[61] = 'O';
    b[62] = 'O';
    b[63] = 'K'; // type
    b[64] = 'M';
    b[65] = 'O';
    b[66] = 'B';
    b[67] = 'I'; // creator
    return b;
  }

  /** Returns a complete minimal PCM WAV file generated by javax.sound.sampled. */
  private static byte[] buildWavBytes() throws Exception {
    ByteArrayOutputStream baos = new ByteArrayOutputStream();
    AudioFormat fmt = new AudioFormat(44100, 16, 2, true, false);
    byte[] silence = new byte[4]; // 1 stereo sample = 4 bytes
    try (AudioInputStream ais = new AudioInputStream(new ByteArrayInputStream(silence), fmt, 1)) {
      AudioSystem.write(ais, AudioFileFormat.Type.WAVE, baos);
    }
    return baos.toByteArray();
  }

  /** Returns a complete minimal AIFF file generated by javax.sound.sampled. */
  private static byte[] buildAiffBytes() throws Exception {
    ByteArrayOutputStream baos = new ByteArrayOutputStream();
    AudioFormat fmt = new AudioFormat(44100, 16, 2, true, true); // big-endian for AIFF
    byte[] silence = new byte[4];
    try (AudioInputStream ais = new AudioInputStream(new ByteArrayInputStream(silence), fmt, 1)) {
      AudioSystem.write(ais, AudioFileFormat.Type.AIFF, baos);
    }
    return baos.toByteArray();
  }

  /**
   * Returns a raw MPEG-1 Layer III byte sequence spanning two complete sync frames. Frame size for
   * 128kbps/44100Hz/stereo = 417 bytes. libmagic validates two consecutive sync headers before
   * committing to audio/mpeg.
   */
  private static byte[] buildMp3Bytes() {
    byte[] b = new byte[834]; // 2 × 417 bytes (two 128kbps stereo frames)
    // Frame 1 header: MPEG-1, Layer III, 128kbps, 44100Hz, stereo (joint stereo = 0x90)
    b[0] = (byte) 0xFF;
    b[1] = (byte) 0xFB;
    b[2] = (byte) 0x90;
    b[3] = 0x00;
    // Frame 2 header at offset 417
    b[417] = (byte) 0xFF;
    b[418] = (byte) 0xFB;
    b[419] = (byte) 0x90;
    b[420] = 0x00;
    return b;
  }

  /** Returns a minimal BMP file with a complete BITMAPINFOHEADER (54 bytes, 1×1 pixel, 24bpp). */
  private static byte[] buildBmpBytes() {
    byte[] b = new byte[54];
    b[0] = 'B';
    b[1] = 'M'; // signature
    b[2] = 54; // file size (little-endian, fits in 1 byte here)
    b[10] = 54; // pixel data offset
    b[14] = 40; // BITMAPINFOHEADER size = 40
    b[18] = 1; // width = 1
    b[22] = 1; // height = 1
    b[26] = 1; // color planes = 1
    b[28] = 24; // bits per pixel = 24
    return b;
  }

  /** Returns a minimal valid WebP file in VP8L (lossless) format (32 bytes). */
  private static byte[] buildWebpBytes() {
    return new byte[] {
      0x52,
      0x49,
      0x46,
      0x46, // "RIFF"
      0x1A,
      0x00,
      0x00,
      0x00, // chunk size = 26
      0x57,
      0x45,
      0x42,
      0x50, // "WEBP"
      0x56,
      0x50,
      0x38,
      0x4C, // "VP8L" chunk type
      0x0D,
      0x00,
      0x00,
      0x00, // VP8L chunk size = 13
      0x2F, // VP8L signature byte
      0x00,
      0x00,
      0x00,
      0x00, // 1×1, no alpha, version 0
      (byte) 0xFE,
      (byte) 0xFF,
      0x03, // transform data
      (byte) 0xFE,
      (byte) 0xFF,
      0x03,
      0x00 // pixel data
    };
  }

  /**
   * Returns a minimal M4A ftyp box (ISO Base Media File Format with "M4A " major brand). On macOS
   * libmagic returns {@code audio/x-m4a}; on Linux it typically returns {@code audio/mp4}. Both
   * satisfy {@code isAudio()}.
   */
  private static byte[] buildM4aBytes() {
    return new byte[] {
      0x00, 0x00, 0x00, 0x20, // box size = 32
      0x66, 0x74, 0x79, 0x70, // "ftyp"
      0x4D, 0x34, 0x41, 0x20, // major brand = "M4A "
      0x00, 0x00, 0x00, 0x00, // minor version
      0x4D, 0x34, 0x41, 0x20, // compatible: "M4A "
      0x4D, 0x34, 0x42, 0x20, // compatible: "M4B "
      0x69, 0x73, 0x6F, 0x6D, // compatible: "isom"
      0x69, 0x73, 0x6F, 0x32 // compatible: "iso2"
    };
  }

  /**
   * Returns a minimal M4B ftyp box (audiobook variant with "M4B " major brand). Detection behaviour
   * is identical to M4A at the container level.
   */
  private static byte[] buildM4bBytes() {
    return new byte[] {
      0x00, 0x00, 0x00, 0x20, // box size = 32
      0x66, 0x74, 0x79, 0x70, // "ftyp"
      0x4D, 0x34, 0x42, 0x20, // major brand = "M4B " (audiobook)
      0x00, 0x00, 0x00, 0x00,
      0x4D, 0x34, 0x42, 0x20,
      0x4D, 0x34, 0x41, 0x20,
      0x69, 0x73, 0x6F, 0x6D,
      0x69, 0x73, 0x6F, 0x32
    };
  }

  /**
   * Returns a minimal OGG/Opus page (47 bytes) with a valid OpusHead identification header.
   * libmagic identifies the OGG container regardless of the codec carried inside.
   */
  private static byte[] buildOpusBytes() {
    byte[] b = new byte[47];
    b[0] = 0x4F;
    b[1] = 0x67;
    b[2] = 0x67;
    b[3] = 0x53; // "OggS"
    b[4] = 0x00; // stream structure version
    b[5] = 0x02; // header type: beginning-of-stream
    // granule position [6..13] = 0
    // serial/sequence numbers [14..21] = 0
    // checksum [22..25] = 0 (CRC not validated for content detection)
    b[26] = 0x01; // page_segments = 1
    b[27] = 0x13; // segment size = 19 bytes (OpusHead)
    // OpusHead identification header
    b[28] = 0x4F;
    b[29] = 0x70;
    b[30] = 0x75;
    b[31] = 0x73; // "Opus"
    b[32] = 0x48;
    b[33] = 0x65;
    b[34] = 0x61;
    b[35] = 0x64; // "Head"
    b[36] = 0x01; // version = 1
    b[37] = 0x02; // channel count = 2 (stereo)
    b[38] = 0x38;
    b[39] = 0x01; // pre-skip = 312 (little-endian)
    b[40] = 0x44;
    b[41] = (byte) 0xAC;
    b[42] = 0x00;
    b[43] = 0x00; // input sample rate = 44100
    b[44] = 0x00;
    b[45] = 0x00; // output gain = 0
    b[46] = 0x00; // channel mapping family = 0 (stereo)
    return b;
  }

  /**
   * Builds a minimal EPUB-compliant ZIP: a STORED "mimetype" entry with no extra field and no
   * data-descriptor, placing "application/epub+zip" at byte offset 38, exactly where the libmagic
   * EPUB rule matches. No central directory is included; some databases may fall back to
   * application/zip.
   */
  private static byte[] buildEpubBytes() {
    byte[] filename = "mimetype".getBytes(StandardCharsets.UTF_8); // 8 bytes
    byte[] content = "application/epub+zip".getBytes(StandardCharsets.UTF_8); // 20 bytes
    CRC32 crc32 = new CRC32();
    crc32.update(content);
    int crc = (int) crc32.getValue();
    // Local file header (30 bytes) + filename (8) + content (20) = 58 bytes total
    // At offset 30+0 = 30: "mimetype" | at offset 38: "application/epub+zip"
    byte[] zip = new byte[30 + filename.length + content.length];
    zip[0] = 0x50;
    zip[1] = 0x4B;
    zip[2] = 0x03;
    zip[3] = 0x04; // PK\x03\x04
    zip[4] = 0x0A;
    zip[5] = 0x00; // version needed = 1.0 (stored)
    // general purpose flags [6..7] = 0
    // compression method [8..9] = 0 (STORED)
    // mod time/date [10..13] = 0
    zip[14] = (byte) (crc & 0xFF);
    zip[15] = (byte) ((crc >> 8) & 0xFF);
    zip[16] = (byte) ((crc >> 16) & 0xFF);
    zip[17] = (byte) ((crc >> 24) & 0xFF);
    zip[18] = (byte) (content.length & 0xFF); // compressed size
    zip[22] = (byte) (content.length & 0xFF); // uncompressed size
    zip[26] = (byte) filename.length; // filename length = 8
    zip[27] = 0x00;
    zip[28] = 0x00;
    zip[29] = 0x00; // extra field length = 0 (critical, no offset shift)
    System.arraycopy(filename, 0, zip, 30, filename.length);
    System.arraycopy(content, 0, zip, 30 + filename.length, content.length);
    return zip;
  }

  /** Builds a complete ZIP file via ZipOutputStream (used for ZIP and CBZ tests). */
  private static byte[] buildZipBytes() throws IOException {
    ByteArrayOutputStream baos = new ByteArrayOutputStream();
    try (ZipOutputStream zos = new ZipOutputStream(baos)) {
      zos.putNextEntry(new ZipEntry("readme.txt"));
      zos.write("hello".getBytes(StandardCharsets.UTF_8));
      zos.closeEntry();
    }
    return baos.toByteArray();
  }

  @Test
  void png() {
    assertEquals("image/png", Magic.detectMimeType(PNG));
  }

  @Test
  void jpeg() {
    assertEquals("image/jpeg", Magic.detectMimeType(JPEG));
  }

  @Test
  void gif() {
    assertEquals("image/gif", Magic.detectMimeType(GIF));
  }

  @Test
  void tiffLittleEndian() {
    assertEquals("image/tiff", Magic.detectMimeType(TIFF_LE));
  }

  @Test
  void tiffBigEndian() {
    assertEquals("image/tiff", Magic.detectMimeType(TIFF_BE));
  }

  @Test
  void svg() {
    assertEquals("image/svg+xml", Magic.detectMimeType(SVG));
  }

  @Test
  void bmp(@TempDir Path tmpDir) throws Exception {
    Path file = tmpDir.resolve("test.bmp");
    Files.write(file, buildBmpBytes());
    String result = Magic.detectMimeType(file);
    assertTrue(result.startsWith("image/"), "BMP must be image/*: " + result);
  }

  @Test
  void webp(@TempDir Path tmpDir) throws Exception {
    Path file = tmpDir.resolve("test.webp");
    Files.write(file, buildWebpBytes());
    assertEquals("image/webp", Magic.detectMimeType(file));
  }

  @Test
  void flac() {
    String result = Magic.detectMimeType(FLAC);
    // libmagic ≥5.39 returns "audio/flac"; older versions returned "audio/x-flac"
    assertTrue(
        result.equals("audio/flac") || result.equals("audio/x-flac"),
        "Expected FLAC MIME type, got: " + result);
  }

  @Test
  void mp3(@TempDir Path tmpDir) throws Exception {
    Path file = tmpDir.resolve("test.mp3");
    Files.write(file, buildMp3Bytes());
    assertEquals("audio/mpeg", Magic.detectMimeType(file));
  }

  @Test
  void wav(@TempDir Path tmpDir) throws Exception {
    Path file = tmpDir.resolve("test.wav");
    Files.write(file, buildWavBytes());
    String result = Magic.detectMimeType(file);
    // "audio/x-wav" (macOS) or "audio/wav" (Linux), both satisfy isAudio()
    assertTrue(
        result.equals("audio/x-wav") || result.equals("audio/wav"),
        "Expected WAV MIME type, got: " + result);
  }

  @Test
  void aiff(@TempDir Path tmpDir) throws Exception {
    Path file = tmpDir.resolve("test.aiff");
    Files.write(file, buildAiffBytes());
    String result = Magic.detectMimeType(file);
    assertTrue(result.startsWith("audio/"), "AIFF must be audio/*: " + result);
  }

  @Test
  void m4aAudiobook(@TempDir Path tmpDir) throws Exception {
    // M4A containers use the "M4A " ftyp brand.
    // macOS libmagic: audio/x-m4a | Linux libmagic: audio/mp4, both satisfy isAudio()
    Path file = tmpDir.resolve("test.m4a");
    Files.write(file, buildM4aBytes());
    String result = Magic.detectMimeType(file);
    assertTrue(result.startsWith("audio/"), "M4A must be audio/*: " + result);
  }

  @Test
  void m4bAudiobook(@TempDir Path tmpDir) throws Exception {
    // M4B is chaptered audio in the same MPEG-4 container as M4A.
    Path file = tmpDir.resolve("test.m4b");
    Files.write(file, buildM4bBytes());
    String result = Magic.detectMimeType(file);
    assertTrue(result.startsWith("audio/"), "M4B audiobook must be audio/*: " + result);
  }

  @Test
  void oggOpus(@TempDir Path tmpDir) throws Exception {
    Path file = tmpDir.resolve("test.opus");
    Files.write(file, buildOpusBytes());
    String result = Magic.detectMimeType(file);
    // libmagic returns audio/ogg for the OGG container regardless of codec
    assertTrue(result.startsWith("audio/"), "OGG/Opus must be audio/*: " + result);
  }

  @Test
  void zip() throws IOException {
    assertEquals("application/zip", Magic.detectMimeType(buildZipBytes()));
  }

  @Test
  void rarV4() {
    String result = Magic.detectMimeType(RAR_V4);
    // libmagic 5.45+ maps both RAR v4 and v5 to application/vnd.rar (IANA type)
    assertTrue(result.contains("rar"), "RAR v4 must be identified as RAR: " + result);
  }

  @Test
  void rarV5() {
    String result = Magic.detectMimeType(RAR_V5);
    assertEquals("application/vnd.rar", result, "RAR v5 must use the IANA type");
  }

  @Test
  void rarV4AndV5BothDetectedAsRar() {
    // In libmagic 5.45+ both v4 and v5 return application/vnd.rar (IANA registered type).
    // Grimmory's isArchive() uses mime.contains("rar") so both satisfy the contract.
    String mimeV4 = Magic.detectMimeType(RAR_V4);
    String mimeV5 = Magic.detectMimeType(RAR_V5);
    assertTrue(mimeV4.contains("rar"), "RAR v4 must contain 'rar': " + mimeV4);
    assertTrue(mimeV5.contains("rar"), "RAR v5 must contain 'rar': " + mimeV5);
  }

  @Test
  void sevenZip() {
    assertEquals("application/x-7z-compressed", Magic.detectMimeType(SEVENZIP));
  }

  @Test
  void gzip() {
    String result = Magic.detectMimeType(GZIP);
    // "application/gzip" (IANA) or "application/x-gzip" (legacy)
    assertTrue(
        result.equals("application/gzip") || result.equals("application/x-gzip"),
        "Expected GZip MIME type, got: " + result);
  }

  // CBZ and CBR are comic archives, they use the same container as ZIP and RAR respectively
  @Test
  void cbzIsZip() throws IOException {
    assertEquals("application/zip", Magic.detectMimeType(buildZipBytes()));
  }

  @Test
  void cbrIsRar() {
    assertTrue(Magic.detectMimeType(RAR_V4).contains("rar"), "CBR (RAR) must contain 'rar'");
  }

  @Test
  void pdf() {
    assertEquals(
        "application/pdf", Magic.detectMimeType("%PDF-1.7".getBytes(StandardCharsets.US_ASCII)));
  }

  @Test
  void epub(@TempDir Path tmpDir) throws Exception {
    // Write the EPUB-spec ZIP (stored "mimetype" entry at offset 0) to a real file.
    // EPUB detection depends on the libmagic database: modern rules match the pattern
    // "mimetypeapplication/epub+zip" at offset 38 and return application/epub+zip; databases
    // without the EPUB rule fall back to the generic ZIP detector. Both are acceptable since
    // EPUB IS a ZIP container and Grimmory detects EPUBs by file extension in practice.
    Path file = tmpDir.resolve("test.epub");
    Files.write(file, buildEpubBytes());
    String result = Magic.detectMimeType(file);
    assertTrue(
        result.equals("application/epub+zip") || result.contains("zip"),
        "EPUB must be epub+zip or zip-based container, got: " + result);
  }

  @Test
  void mobi() {
    String result = Magic.detectMimeType(MOBI);
    assertTrue(
        result.contains("mobipocket") || result.contains("mobi"),
        "MOBI must be identified as Mobipocket ebook, got: " + result);
  }

  @Test
  void fb2() {
    byte[] fb2 =
        ("<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
                + "<FictionBook xmlns=\"http://www.gribuser.ru/xml/fictionbook/2.0\">"
                + "<body><section><p>Test</p></section></body></FictionBook>")
            .getBytes(StandardCharsets.UTF_8);
    String result = Magic.detectMimeType(fb2);
    // libmagic may return application/x-fictionbook+xml (if the rule exists) or text/xml
    assertTrue(
        result.contains("fictionbook") || result.contains("xml"),
        "FB2 must be fictionbook or xml, got: " + result);
  }

  @Test
  void detectMimeTypeFromInputStream() throws IOException {
    try (var in = new ByteArrayInputStream(PNG)) {
      assertEquals("image/png", Magic.detectMimeType(in));
    }
  }

  @Test
  void detectFromInputStreamViaInstance() throws IOException {
    try (Magic magic = Magic.open(MagicFlags.MAGIC_MIME_TYPE);
        var in = new ByteArrayInputStream(JPEG)) {
      assertEquals("image/jpeg", magic.detect(in));
    }
  }

  @Test
  void detectMimeTypeFromSlice() {
    // Prepend 16 bytes of garbage; detect only the PDF slice at offset 16
    byte[] pdfBytes = "%PDF-1.7".getBytes(StandardCharsets.US_ASCII);
    byte[] padded = new byte[16 + pdfBytes.length];
    System.arraycopy(pdfBytes, 0, padded, 16, pdfBytes.length);
    assertEquals("application/pdf", Magic.detectMimeType(padded, 16, pdfBytes.length));
  }

  @Test
  void setFlagsMutatesDetectionMode() {
    try (Magic magic = Magic.open(MagicFlags.MAGIC_NONE)) {
      String description = magic.detect(PNG);
      // MAGIC_NONE returns a human-readable description, not a MIME type
      assertFalse(
          description.contains("/"),
          "MAGIC_NONE should return textual description, not a MIME type. Got: " + description);

      magic.setFlags(MagicFlags.MAGIC_MIME_TYPE);
      assertEquals(
          "image/png", magic.detect(PNG), "After setFlags(MIME_TYPE), must return MIME type");
    }
  }

  @Test
  void setFlagsOnClosedCookieThrows() {
    Magic magic = Magic.open(MagicFlags.MAGIC_NONE);
    magic.close();
    assertThrows(MagicException.class, () -> magic.setFlags(MagicFlags.MAGIC_MIME_TYPE));
  }

  /**
   * Verifies all audio formats used by Grimmory satisfy {@code isAudio(mime)} which is implemented
   * as {@code mime != null && mime.startsWith("audio/")}. Uses file-based detection because
   * Grimmory detects files from disk.
   */
  @Test
  void allAudioFormatsStartWithAudio(@TempDir Path tmpDir) throws Exception {
    record Format(String name, byte[] bytes, String ext) {}

    var formats =
        List.of(
            new Format("MP3", buildMp3Bytes(), ".mp3"),
            new Format("FLAC", FLAC, ".flac"),
            new Format("WAV", buildWavBytes(), ".wav"),
            new Format("AIFF", buildAiffBytes(), ".aiff"),
            new Format("M4A", buildM4aBytes(), ".m4a"),
            new Format("M4B", buildM4bBytes(), ".m4b"),
            new Format("OGG/Opus", buildOpusBytes(), ".opus"));
    for (Format f : formats) {
      Path file = tmpDir.resolve("test" + f.ext());
      Files.write(file, f.bytes());
      String mime = Magic.detectMimeType(file);
      assertTrue(mime.startsWith("audio/"), f.name() + " failed isAudio() contract. Got: " + mime);
    }
  }

  /**
   * Verifies all image formats satisfy {@code isImage(mime)} = {@code mime.startsWith("image/")}.
   */
  @Test
  void allImageFormatsStartWithImage(@TempDir Path tmpDir) throws Exception {
    record Format(String name, byte[] bytes, String ext) {}

    var formats =
        List.of(
            new Format("PNG", PNG, ".png"),
            new Format("JPEG", JPEG, ".jpg"),
            new Format("GIF", GIF, ".gif"),
            new Format("TIFF-LE", TIFF_LE, ".tiff"),
            new Format("TIFF-BE", TIFF_BE, ".tiff"),
            new Format("SVG", SVG, ".svg"),
            new Format("BMP", buildBmpBytes(), ".bmp"),
            new Format("WebP", buildWebpBytes(), ".webp"));
    for (Format f : formats) {
      Path file = tmpDir.resolve("test" + f.ext());
      Files.write(file, f.bytes());
      String mime = Magic.detectMimeType(file);
      assertTrue(mime.startsWith("image/"), f.name() + " failed isImage() contract. Got: " + mime);
    }
  }

  /**
   * Verifies that archive MIME types satisfy Grimmory's {@code isArchive()} logic which uses
   * substring checks: {@code mime.contains("zip")}, {@code mime.contains("rar")}, {@code
   * mime.contains("7z")}, {@code mime.contains("gzip")}.
   */
  @Test
  void archiveMimesSatisfyIsArchiveContract() throws IOException {
    assertTrue(Magic.detectMimeType(buildZipBytes()).contains("zip"), "ZIP must contain 'zip'");
    assertTrue(Magic.detectMimeType(RAR_V4).contains("rar"), "RAR v4 must contain 'rar'");
    assertTrue(Magic.detectMimeType(RAR_V5).contains("rar"), "RAR v5 must contain 'rar'");
    assertTrue(Magic.detectMimeType(SEVENZIP).contains("7z"), "7-Zip must contain '7z'");
    assertTrue(Magic.detectMimeType(GZIP).contains("gzip"), "GZip must contain 'gzip'");
  }
}
